// dir: [
//   "C:/Users/{{root_user}}",
//   "C:/Users/{{root_user}}/Desktop",
//   "C:/Users/{{root_user}}/Downloads",
//   "C:/Users/{{root_user}}/Documents",
//   "C:/Users/{{root_user}}/Music",
//   "C:/Users/{{root_user}}/Pictures",
//   "C:/Users/{{root_user}}/Videos",
//   "C:/Users/{{root_user}}/Desktop/New folder",
//   "C:/Users/{{root_user}}/Documents",
// ],
