export const windows7Folders = [
  "C:/Users/Public",
  "C:/Program Files",
  "C:/Program Files (x86)",
  "C:/Windows",
  "C:/Users/{{root_user}}/Favorites",
  "C:/Users/{{root_user}}/AppData",
  "C:/Users/{{root_user}}/AppData/Local",
  "C:/Users/{{root_user}}/AppData/Roaming",
  "C:/Users/{{root_user}}/AppData/LocalLow",
  "C:/Users/{{root_user}}/Links",
  "C:/Users/{{root_user}}/Saved Games",
  "C:/Users/{{root_user}}/Searches",
  "C:/Recycle Bin",
  "C:/Network",
  "C:/Control Panel",
  "C:/Libraries/Desktop",
  "C:/Libraries/Documents",
  "C:/Libraries/Downloads",
  "C:/Libraries/Music",
  "C:/Libraries/Pictures",
  "C:/Libraries/Videos",
];

// dir: [
//   "C:/Users/{{root_user}}",
//   "C:/Users/{{root_user}}/Desktop",
//   "C:/Users/{{root_user}}/Downloads",
//   "C:/Users/{{root_user}}/Documents",
//   "C:/Users/{{root_user}}/Music",
//   "C:/Users/{{root_user}}/Pictures",
//   "C:/Users/{{root_user}}/Videos",
//   "C:/Users/{{root_user}}/Desktop/New folder",
//   "C:/Users/{{root_user}}/Documents",
// ],
